import allure

from src.constants import ConstantsURL, ConstantsUserData
from src.locators.home_page_locators import HomePageLocators
from src.locators.order_page_locators import OrderPageLocators
from src.pages.base_page import BasePage


class HomePage(BasePage):
    @allure.step('Наследование драйвера')
    def __init__(self, driver):
        super().__init__(driver)

    @allure.step('Возвращаем кнопку «Отменить заказ» на странице заказа для тестовых данных №1')
    def make_an_order_scooter_one(self):
        self.navigate_to_url(ConstantsURL.HOME_URL)
        search_cookie = self.find_element(HomePageLocators.BUTTON_COOKIE)
        search_cookie.click()
        button_order = self.find_element(HomePageLocators.BUTTON_ORDER_HOME_PAGE)
        self.scroll_to_element(button_order)
        self.find_element_to_be_clickable(button_order)
        button_order.click()
        input_first_name = self.find_element(OrderPageLocators.INPUT_FIRST_NAME)
        input_first_name.send_keys(ConstantsUserData.USER_DATA['first_name'])
        input_last_name = self.find_element(OrderPageLocators.INPUT_LAST_NAME)
        input_last_name.send_keys(ConstantsUserData.USER_DATA['last_name'])
        input_address = self.find_element(OrderPageLocators.INPUT_ADDRESS)
        input_address.send_keys(ConstantsUserData.ADDRESS_ONE)
        list_stations = self.find_element(OrderPageLocators.INPUT_SUBWAY)
        list_stations.click()
        choose_subway = self.find_element(OrderPageLocators.CHOOSE_SUBWAY_STATION_CULTURE_PARK)
        self.scroll_to_element(choose_subway)
        self.find_element_to_be_clickable(choose_subway)
        choose_subway.click()
        input_phone = self.find_element(OrderPageLocators.INPUT_PHONE_NUMBER)
        input_phone.send_keys(ConstantsUserData.PHONE_NUMBER_ONE)
        button_further = self.find_element(OrderPageLocators.BUTTON_FURTHER)
        button_further.click()
        input_date_order = self.find_element(OrderPageLocators.INPUT_DATE_ORDER)
        self.find_element_to_be_clickable(input_date_order)
        input_date_order.send_keys(ConstantsUserData.DATE_ONE)
        text_modal_window = self.find_element(OrderPageLocators.TEXT_MODAL_WINDOW)
        text_modal_window.click()
        choose_rental = self.find_element(OrderPageLocators.CHOOSE_RENTAL_PERIOD)
        choose_rental.click()
        choose_rental_two_days = self.find_element(OrderPageLocators.CHOOSE_RENTAL_PERIOD_TWO_DAYS)
        choose_rental_two_days.click()
        choose_black_color = self.find_element(OrderPageLocators.CHOOSE_BLACK_COLOR_SCOOTER)
        choose_black_color.click()
        input_for_comment = self.find_element(OrderPageLocators.INPUT_COMMENT_FOR_COURIER)
        input_for_comment.send_keys(ConstantsUserData.COMMENT_FOR_COURIER_ONE)
        button_order_page = self.find_element(OrderPageLocators.BUTTON_ORDER)
        button_order_page.click()
        button_yes = self.find_element(OrderPageLocators.BUTTON_YES)
        button_yes.click()
        button_view_status = self.find_element(OrderPageLocators.BUTTON_VIEW_STATUS_ORDER)
        button_view_status.click()
        button_cancel_order = self.find_element(OrderPageLocators.BUTTON_CANCEL_ORDER)
        return button_cancel_order

    @allure.step('Возвращаем кнопку «Отменить заказ» на странице заказа для тестовых данных №2')
    def make_an_order_scooter_two(self):
        self.navigate_to_url(ConstantsURL.HOME_URL)
        search_cookie = self.find_element(HomePageLocators.BUTTON_COOKIE)
        search_cookie.click()
        button_order = self.find_element(HomePageLocators.BUTTON_ORDER_HOME_PAGE)
        self.scroll_to_element(button_order)
        self.find_element_to_be_clickable(button_order)
        button_order.click()
        input_first_name = self.find_element(OrderPageLocators.INPUT_FIRST_NAME)
        input_first_name.send_keys(ConstantsUserData.USER_DATA['first_name'])
        input_last_name = self.find_element(OrderPageLocators.INPUT_LAST_NAME)
        input_last_name.send_keys(ConstantsUserData.USER_DATA['last_name'])
        input_address = self.find_element(OrderPageLocators.INPUT_ADDRESS)
        input_address.send_keys(ConstantsUserData.ADDRESS_SECOND)
        list_stations = self.find_element(OrderPageLocators.INPUT_SUBWAY)
        list_stations.click()
        choose_subway = self.find_element(OrderPageLocators.CHOOSE_SUBWAY_STATION_TULSKAYA)
        self.scroll_to_element(choose_subway)
        self.find_element_to_be_clickable(choose_subway)
        choose_subway.click()
        input_phone = self.find_element(OrderPageLocators.INPUT_PHONE_NUMBER)
        input_phone.send_keys(ConstantsUserData.PHONE_NUMBER_SECOND)
        button_further = self.find_element(OrderPageLocators.BUTTON_FURTHER)
        button_further.click()
        input_date_order = self.find_element(OrderPageLocators.INPUT_DATE_ORDER)
        self.find_element_to_be_clickable(input_date_order)
        input_date_order.send_keys(ConstantsUserData.DATE_SECOND)
        text_modal_window = self.find_element(OrderPageLocators.TEXT_MODAL_WINDOW)
        text_modal_window.click()
        choose_rental = self.find_element(OrderPageLocators.CHOOSE_RENTAL_PERIOD)
        choose_rental.click()
        choose_rental_two_days = self.find_element(OrderPageLocators.CHOOSE_RENTAL_PERIOD_FOUR_DAYS)
        choose_rental_two_days.click()
        choose_black_color = self.find_element(OrderPageLocators.CHOOSE_GREY_COLOR_SCOOTER)
        choose_black_color.click()
        input_for_comment = self.find_element(OrderPageLocators.INPUT_COMMENT_FOR_COURIER)
        input_for_comment.send_keys(ConstantsUserData.COMMENT_FOR_COURIER_SECOND)
        button_order_page = self.find_element(OrderPageLocators.BUTTON_ORDER)
        button_order_page.click()
        button_yes = self.find_element(OrderPageLocators.BUTTON_YES)
        button_yes.click()
        button_view_status = self.find_element(OrderPageLocators.BUTTON_VIEW_STATUS_ORDER)
        button_view_status.click()
        button_cancel_order = self.find_element(OrderPageLocators.BUTTON_CANCEL_ORDER)
        return button_cancel_order
